alter table TICKETSHOP_TRIP add constraint FK_TICKETSHOP_TRIP_ON_TICKETID foreign key (TICKETID_ID) references TICKETSHOP_TICKET(ID);
create index IDX_TICKETSHOP_TRIP_ON_TICKETID on TICKETSHOP_TRIP (TICKETID_ID);
