alter table TICKETSHOP_TRIP add constraint FK_TICKETSHOP_TRIP_ON_PASSENGERID foreign key (PASSENGERID_ID) references TICKETSHOP_PASSENGER(ID);
create index IDX_TICKETSHOP_TRIP_ON_PASSENGERID on TICKETSHOP_TRIP (PASSENGERID_ID);
