alter table TICKETSHOP_STOPS add constraint FK_TICKETSHOP_STOPS_ON_ROUTEID foreign key (ROUTEID_ID) references TICKETSHOP_ROUTES(ID);
create index IDX_TICKETSHOP_STOPS_ON_ROUTEID on TICKETSHOP_STOPS (ROUTEID_ID);
